version: '3'

services:
  mariadbserver:
    image: mariadb:11.1
    container_name: mariadbserver
    environment:
      MYSQL_ROOT_PASSWORD: 'app'
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: 'app'
    ports:
      - 43306:3306
